### ISSUE TITLE
[scrum] 200327

### ISSUE THREAD

**Issue by Hyune-c** [codesquad-member-2020/signup-5#60]
- 어제한 일
  - #8 개인정보 조회 
  - #44 설정 변경 
  - #21 Heroku 배포
    - Dev Branch 배포 
(https://signup-5-dev.herokuapp.com/)
    - DB 접속 가능하게 설정 
(https://signup-5-dev.herokuapp.com/h2-console)
  - FE 테스트를 위한 세션 체크 페이지 배포 
(https://signup-5-dev.herokuapp.com/checkSession)
- 오늘 할 일
  - #21 master 가 merge 되는 경우 Heroku master 도 올릴 예정 
  - 리팩토링
- 오늘 컨디션
  - 양호
- 고민되는 것
  - 오늘 13시 ~ 18시까지  서버 지원이 힘들듯 합니다. 슬랙은 지원 가능하니 불러주세요.
  - 통합 테스트를 어떻게 해야 될까요? #59 에 제 생각을 남겼습니다.

**Comment by delmaSong** [comment]
### 어제 한 일
- 깃 브랜치가 너무 꼬여서 그거 해결하느라 시간을 다 보냈습니다 동료의 도움으로 겨우 해결ㅠ

### 오늘 할 일
- 관심사 화면 기능 개발 완료
- 아이디 중복 기능 구현(ㅅㅓ버랑 통신)

### 오늘 컨디션
- 아주 좋슴다!

### 고민되는 것 
- 오늘 마무리 해야한다니..^^

**Comment by moonelysian** [comment]
### 어제 한 일
리팩토리이잉~

### 오늘 할 일
- 프론트랑 예쁘게 배포하기..

### 오늘 컨디션
😄 

### 고민되는 것
배포..ㅎ

**Comment by seungdeng17** [comment]
늦어서 죄송합니다!

### 어제 한 일
- 로그인, 메인 페이지 만들기
- 로그인 기능 구현
- 확인 된 예외 상황 처리
- 백엔드 팀원 괴롭히기..

### 오늘 할 일
- 어떻게 배포가 이루어 지는지 공부하기
- Set-Cookie 왜 안먹혔는지 알아보기

### 오늘 컨디션
- 좋아요!!

### 고민되는 것
Set-Cookie!!!!!!!

**Comment by crongro** [comment]
백엔드 팀원 괴롭히기. !! 👍
